blank_issues_enabled: false
contact_links:
  - name: Questions & ideas
    url: https://github.com/California-Cadet-Corps/cacc-start/discussions
    about: Use Discussions for questions, ideas, and general conversation.
